## Analísis comparativo de uso de estrategias

In [36]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

#### Importar datos

In [37]:
df_aleman = pd.read_excel("Aleman_Principal.xlsx")

In [38]:
df_chino = pd.read_excel("Chino_Principal.xlsx")

In [39]:
df_ruso = pd.read_excel("Ruso_Principal.xlsx")

In [40]:
df_aleman['Idioma'] = 'Alemán'
df_chino['Idioma'] = 'Chino'
df_ruso['Idioma'] = 'Ruso'

### Estrategias usadas
#### Grupo completo

In [41]:
datasets = [df_aleman,df_chino,df_ruso]
df = pd.concat(datasets, ignore_index=True)
df = df.fillna(0)

In [42]:
#df['ID1'].value_counts() -> comprobar si hay duplicados

In [43]:
columnas_estrategias = [
    col for col in df.columns if col.startswith("E") and "[SQ" in col
]

In [44]:
for col in columnas_estrategias:
    df[col] = (
        df[col]
        .astype(str)
        .str.lower()
        .str.strip()
        .map({"yes": 1, "no": 0})
    )
    
    
    #df_binario = df[columnas_estrategias].replace({"Yes":1,"No":0})
#df_binario
    
#df_binario = df.applymap(lambda x: 1 if str(x).strip() == "Yes" else 0)
#df_binario = (df[columnas_estrategias] == "Yes").astype(int)

#df_estrategias = df[columnas_estrategias]
#df_binario = df_estrategias.applymap(lambda x: 1 if str(x).strip() == "Yes" else 0)

In [45]:
df.head()

,Grupo,Nivel,id,submitdate,lastpage,startlanguage,seed,startdate,datestamp,ipaddr,...,Resumen,Num,interviewtime,groupTime2881,groupTime2882,groupTime2884,groupTime2883,groupTime2885,Kommentar,Idioma
0,LenguaC_Nivel2_A,Principiantes,3.0,2026-04-21 12:02:49,5.0,en,3.276906e+08,2026-04-21 11:19:51,2026-04-21 12:02:49,150.214.27.0,...,3,25.0,2573.8,2509.28,25.94,19.10,6.99,12.49,0,Alemán
1,LenguaC_Nivel2_A,Principiantes,4.0,2026-04-21 11:53:36,5.0,en,6.696777e+08,2026-04-21 11:40:26,2026-04-21 11:53:36,150.214.27.0,...,3,3.0,786.24,664.02,66.89,15.90,5.45,33.98,0,Alemán
2,LenguaC_Nivel2_A,Principiantes,5.0,2026-04-21 11:55:45,5.0,en,1.670875e+09,2026-04-21 11:45:53,2026-04-21 11:55:45,150.214.27.0,...,1?,19.0,589.5,521.60,23.88,25.80,6.29,11.93,0,Alemán
3,LenguaC_Nivel2_A,Principiantes,6.0,2026-04-21 11:54:59,5.0,en,3.323836e+08,2026-04-21 11:46:04,2026-04-21 11:54:59,150.214.27.0,...,1,11.0,530.93,420.44,28.07,50.05,6.47,25.90,0,Alemán
4,LenguaC_Nivel2_A,Principiantes,7.0,2026-04-21 11:54:14,5.0,en,7.128430e+08,2026-04-21 11:46:17,2026-04-21 11:54:14,150.214.27.0,...,3,16.0,473.13,396.46,33.55,13.80,8.20,21.12,0,Alemán

In [46]:
frecuencias_totales = {}

for col in columnas_estrategias:
    codigo_estrategia = col.split("[")[1].split("]")[0]

    votos = df[col].sum()
    frecuencias_totales[codigo_estrategia] = (
        frecuencias_totales.get(codigo_estrategia, 0) + votos
    )

In [47]:
df_resultados = pd.DataFrame(
    list(frecuencias_totales.items()), columns=["Código", "Frecuencia"]
)
total_elecciones = df_resultados["Frecuencia"].sum().astype(int)
df_resultados["Porcentaje"] = np.round(((
    df_resultados["Frecuencia"] / total_elecciones
) * 100), 2)

In [75]:
df_resultados_gen = df_resultados.replace({'SQ001': 'Otros idiomas', 
                        'SQ002': 'Analizar forma',
                        'SQ003': 'Contexto inmediato',
                      'SQ004': 'Contexto general',
                      'SQ005': 'Elementos no verbales',
                      'SQ006': 'Diccionario/Traductor',
                      'SQ007': 'Aplicación IA',
                      'SQ008': 'Preguntar compañero/a',
                      'SQ009': 'Preguntar profesor/a'})
df_resultados_gen

                  Código  Frecuencia  Porcentaje
0          Otros idiomas        71.0        3.59
1         Analizar forma       183.0        9.26
2     Contexto inmediato       279.0       14.11
3       Contexto general       167.0        8.45
4  Elementos no verbales        25.0        1.26
5  Diccionario/Traductor      1042.0       52.71
6          Aplicación IA        61.0        3.09
7  Preguntar compañero/a        65.0        3.29
8   Preguntar profesor/a        84.0        4.25

#### Resultados alemán

In [49]:
columnas_estrategias = [
    col for col in df_aleman.columns if col.startswith("E") and "[SQ" in col
]
df_estrategias = df_aleman[columnas_estrategias]
df_binario = df_estrategias.applymap(lambda x: 1 if str(x).strip() == "Yes" else 0)

In [50]:
frecuencias_totales = {}

for col in df_binario.columns:
    codigo_estrategia = col.split("[")[1].split("]")[0]

    votos = df_binario[col].sum()
    frecuencias_totales[codigo_estrategia] = (
        frecuencias_totales.get(codigo_estrategia, 0) + votos
    )

In [51]:
df_resultados_al = pd.DataFrame(
    list(frecuencias_totales.items()), columns=["Código", "Frecuencia"]
)
total_elecciones = df_resultados_al["Frecuencia"].sum()
df_resultados_al["Porcentaje"] = np.round(((
    df_resultados_al["Frecuencia"] / total_elecciones
) * 100),2)

In [52]:
df_resultados_al = df_resultados_al.replace({'SQ001': 'Otros idiomas', 
                        'SQ002': 'Analizar forma',
                        'SQ003': 'Contexto inmediato',
                      'SQ004': 'Contexto general',
                      'SQ005': 'Elementos no verbales',
                      'SQ006': 'Diccionario/Traductor',
                      'SQ007': 'Aplicación IA',
                      'SQ008': 'Preguntar compañero/a',
                      'SQ009': 'Preguntar profesor/a'})
#df_resultados_al

#### Resultados chino

In [53]:
columnas_estrategias = [
    col for col in df_chino.columns if col.startswith("E") and "[SQ" in col
]
df_estrategias = df_chino[columnas_estrategias]
df_binario = df_estrategias.applymap(lambda x: 1 if str(x).strip() == "Yes" else 0)

In [54]:
frecuencias_totales = {}

for col in df_binario.columns:
    codigo_estrategia = col.split("[")[1].split("]")[0]

    votos = df_binario[col].sum()
    frecuencias_totales[codigo_estrategia] = (
        frecuencias_totales.get(codigo_estrategia, 0) + votos
    )

In [55]:
df_resultados_chino = pd.DataFrame(
    list(frecuencias_totales.items()), columns=["Código", "Frecuencia"]
)
total_elecciones = df_resultados_chino["Frecuencia"].sum()
df_resultados_chino["Porcentaje"] = np.round(((
    df_resultados_chino["Frecuencia"] / total_elecciones
) * 100), 2)

In [56]:
df_resultados_chino = df_resultados_chino.replace({'SQ001': 'Otros idiomas', 
                        'SQ002': 'Analizar forma',
                        'SQ003': 'Contexto inmediato',
                      'SQ004': 'Contexto general',
                      'SQ005': 'Elementos no verbales',
                      'SQ006': 'Diccionario/Traductor',
                      'SQ007': 'Aplicación IA',
                      'SQ008': 'Preguntar compañero/a',
                      'SQ009': 'Preguntar profesor/a'})
#df_resultados_chino

#### Resultados ruso

In [57]:
columnas_estrategias = [
    col for col in df_ruso.columns if col.startswith("E") and "[SQ" in col
]
df_estrategias = df_ruso[columnas_estrategias]
df_binario = df_estrategias.applymap(lambda x: 1 if str(x).strip() == "Yes" else 0)

In [58]:
frecuencias_totales = {}

for col in df_binario.columns:
    codigo_estrategia = col.split("[")[1].split("]")[0]

    votos = df_binario[col].sum()
    frecuencias_totales[codigo_estrategia] = (
        frecuencias_totales.get(codigo_estrategia, 0) + votos
    )

In [59]:
df_resultados_ruso = pd.DataFrame(
    list(frecuencias_totales.items()), columns=["Código", "Frecuencia"]
)
total_elecciones = df_resultados_ruso["Frecuencia"].sum()
df_resultados_ruso["Porcentaje"] = np.round(((
    df_resultados_ruso["Frecuencia"] / total_elecciones
) * 100), 2)

In [60]:
df_resultados_ruso = df_resultados_ruso.replace({'SQ001': 'Otros idiomas', 
                        'SQ002': 'Analizar forma',
                        'SQ003': 'Contexto inmediato',
                      'SQ004': 'Contexto general',
                      'SQ005': 'Elementos no verbales',
                      'SQ006': 'Diccionario/Traductor',
                      'SQ007': 'Aplicación IA',
                      'SQ008': 'Preguntar compañero/a',
                      'SQ009': 'Preguntar profesor/a'})
#df_resultados_ruso

#### Tabla completa por idiomas

In [61]:
df_resultados_comp = df_resultados_al.drop(columns=['Frecuencia'])
#df_resultados_comp['Alemán'] = df_resultados_al['Porcentaje']
df_resultados_comp = df_resultados_comp.rename(columns={'Porcentaje':'Alemán'})
df_resultados_comp['Chino'] = df_resultados_chino['Porcentaje']
df_resultados_comp['Ruso'] = df_resultados_ruso['Porcentaje']
df_resultados_comp['Total'] = df_resultados_gen['Porcentaje']
df_resultados_comp
#

                  Código  Alemán  Chino   Ruso  Total
0          Otros idiomas    4.95   0.00   3.74   3.59
1         Analizar forma   12.80   6.18   2.18   9.26
2     Contexto inmediato   12.99  26.91   8.10  14.11
3       Contexto general    6.92  21.82   0.93   8.45
4  Elementos no verbales    0.93   4.36   0.00   1.26
5  Diccionario/Traductor   56.07  34.55  52.02  52.71
6          Aplicación IA    3.36   1.82   5.92   3.09
7  Preguntar compañero/a    1.96   3.64   7.48   3.29
8   Preguntar profesor/a    0.00   0.73  19.63   4.25

In [62]:
df_resultados_comp.to_excel('Estrategias_porcentajes.xlsx')

#### Resultados principiantes

In [71]:
df_prin = df[df['Nivel'] == 'Principiantes']
df_int = df[df['Nivel'] == 'Intermedio']

In [80]:
frecuencias_totales = {}

for col in columnas_estrategias:
    codigo_estrategia = col.split("[")[1].split("]")[0]

    votos = df_prin[col].sum()
    frecuencias_totales[codigo_estrategia] = (
        frecuencias_totales.get(codigo_estrategia, 0) + votos
    )

In [81]:
df_resultados_prin = pd.DataFrame(
    list(frecuencias_totales.items()), columns=["Código", "Frecuencia"]
)
total_elecciones = df_resultados_prin["Frecuencia"].sum()
df_resultados_prin["Porcentaje"] = np.round(((
    df_resultados_prin["Frecuencia"] / total_elecciones
) * 100), 2)

In [82]:
df_resultados_prin = df_resultados_prin.replace({'SQ001': 'Otros idiomas', 
                        'SQ002': 'Analizar forma',
                        'SQ003': 'Contexto inmediato',
                      'SQ004': 'Contexto general',
                      'SQ005': 'Elementos no verbales',
                      'SQ006': 'Diccionario/Traductor',
                      'SQ007': 'Aplicación IA',
                      'SQ008': 'Preguntar compañero/a',
                      'SQ009': 'Preguntar profesor/a'})
df_resultados_prin

                  Código  Frecuencia  Porcentaje
0          Otros idiomas        44.0        3.78
1         Analizar forma       103.0        8.86
2     Contexto inmediato       182.0       15.65
3       Contexto general       115.0        9.89
4  Elementos no verbales        20.0        1.72
5  Diccionario/Traductor       580.0       49.87
6          Aplicación IA        38.0        3.27
7  Preguntar compañero/a        39.0        3.35
8   Preguntar profesor/a        42.0        3.61

#### Resultados intermedio

In [83]:
frecuencias_totales = {}

for col in columnas_estrategias:
    codigo_estrategia = col.split("[")[1].split("]")[0]

    votos = df_int[col].sum()
    frecuencias_totales[codigo_estrategia] = (
        frecuencias_totales.get(codigo_estrategia, 0) + votos
    )

In [84]:
df_resultados_int = pd.DataFrame(
    list(frecuencias_totales.items()), columns=["Código", "Frecuencia"]
)
total_elecciones = df_resultados_int["Frecuencia"].sum()
df_resultados_int["Porcentaje"] = np.round(((
    df_resultados_int["Frecuencia"] / total_elecciones
) * 100), 2)

In [85]:
df_resultados_int = df_resultados_int.replace({'SQ001': 'Otros idiomas', 
                        'SQ002': 'Analizar forma',
                        'SQ003': 'Contexto inmediato',
                      'SQ004': 'Contexto general',
                      'SQ005': 'Elementos no verbales',
                      'SQ006': 'Diccionario/Traductor',
                      'SQ007': 'Aplicación IA',
                      'SQ008': 'Preguntar compañero/a',
                      'SQ009': 'Preguntar profesor/a'})
df_resultados_int

                  Código  Frecuencia  Porcentaje
0          Otros idiomas        27.0        3.32
1         Analizar forma        80.0        9.83
2     Contexto inmediato        97.0       11.92
3       Contexto general        52.0        6.39
4  Elementos no verbales         5.0        0.61
5  Diccionario/Traductor       462.0       56.76
6          Aplicación IA        23.0        2.83
7  Preguntar compañero/a        26.0        3.19
8   Preguntar profesor/a        42.0        5.16

#### Tabla completa por niveles

In [88]:
df_resultados_nivel = df_resultados_prin.drop(columns=['Frecuencia'])
df_resultados_nivel = df_resultados_prin.rename(columns={'Porcentaje':'Principiantes'})
df_resultados_nivel['Intermedio'] = df_resultados_int['Porcentaje']
df_resultados_nivel['Total'] = df_resultados_gen['Porcentaje']
df_resultados_nivel = df_resultados_nivel.drop(columns=['Frecuencia'])
df_resultados_nivel

                  Código  Principiantes  Intermedio  Total
0          Otros idiomas           3.78        3.32   3.59
1         Analizar forma           8.86        9.83   9.26
2     Contexto inmediato          15.65       11.92  14.11
3       Contexto general           9.89        6.39   8.45
4  Elementos no verbales           1.72        0.61   1.26
5  Diccionario/Traductor          49.87       56.76  52.71
6          Aplicación IA           3.27        2.83   3.09
7  Preguntar compañero/a           3.35        3.19   3.29
8   Preguntar profesor/a           3.61        5.16   4.25

In [89]:
df_resultados_nivel.to_excel('Estrategias_porcentajes_nivel.xlsx')