## Análisis Ruso

In [26]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

#### Importar datos

In [27]:
df = pd.read_pickle("data_final")

In [28]:
df = df[df["Idioma"] == "Ruso"]

In [29]:
df_voc = pd.read_excel("Ruso_Voc.xlsx")

##### Uso de tipo de estrategias en el grupo

Estrategias usadas (a elegir, selección múltiple):
- SQ001: Usar mis conocimientos de otros idiomas (lengua materna u otras lenguas extranjeras)
- SQ002: Analizar la forma de la palabra o sus partes
- SQ003: Sacar conclusiones del contexto inmediato (p.ej. relación con otras palabras en la frase)
- SQ004: Sacar conclusiones del contexto general (p.ej. tema del texto o de la clase)
- SQ005: Fijarme en elementos no verbales (p.ej. imágenes, el formato del texto)
- SQ006: Consultar un diccionario o un traductor online
- SQ007: Usar una aplicación de Inteligencia Artificial (p.ej. Chat GPT)
- SQ008: Preguntar a un/a compañero/a
- SQ009: Preguntar al/a la docente

In [30]:
columnas_estrategias = [
    col for col in df.columns if col.startswith("E") and "[SQ" in col
]

In [31]:
frecuencias_totales = {}

for col in columnas_estrategias:
    codigo_estrategia = col.split("[")[1].split("]")[0]

    votos = df[col].sum()
    frecuencias_totales[codigo_estrategia] = (
        frecuencias_totales.get(codigo_estrategia, 0) + votos
    )

In [32]:
df_resultados = pd.DataFrame(
    list(frecuencias_totales.items()), columns=["Estrategia", "Frecuencia"]
)
total_elecciones = df_resultados["Frecuencia"].sum().astype(int)
df_resultados["Porcentaje"] = np.round(((
    df_resultados["Frecuencia"] / total_elecciones
) * 100), 2)

In [33]:
df_resultados_gen = df_resultados.replace({'SQ001': 'Otros idiomas', 
                        'SQ002': 'Analizar forma',
                        'SQ003': 'Contexto inmediato',
                      'SQ004': 'Contexto general',
                      'SQ005': 'Elementos no verbales',
                      'SQ006': 'Diccionario/Traductor',
                      'SQ007': 'Aplicación IA',
                      'SQ008': 'Preguntar compañero/a',
                      'SQ009': 'Preguntar profesor/a'})
df_resultados_gen

              Estrategia  Frecuencia  Porcentaje
0          Otros idiomas        12.0        3.74
1         Analizar forma         7.0        2.18
2     Contexto inmediato        26.0        8.10
3       Contexto general         3.0        0.93
4  Elementos no verbales         0.0        0.00
5  Diccionario/Traductor       167.0       52.02
6          Aplicación IA        19.0        5.92
7  Preguntar compañero/a        24.0        7.48
8   Preguntar profesor/a        63.0       19.63

##### Palabras marcadas como nuevas

In [34]:
df['Num'].describe().round(2)

count    26.00
mean     12.92
std       7.30
min       0.00
25%       9.00
50%      13.00
75%      16.75
max      33.00
Name: Num, dtype: float64

##### Número de estrategias indicadas (total y por tipo de estrategias)

In [35]:
columnas_estrategias_totales = [
    col for col in df.columns if col.startswith("Total")]

In [36]:
df[columnas_estrategias_totales].describe().round(2)

,Total_SQ001,Total_SQ002,Total_SQ003,Total_SQ004,Total_SQ005,Total_SQ006,Total_SQ007,Total_SQ008,Total_SQ009,Total_Estrategias,Total_Palabras_Buscadas
count,26.00,26.00,26.0,26.00,26.0,26.00,26.00,26.00,26.00,26.00,26.00
mean,0.46,0.27,1.0,0.12,0.0,6.42,0.73,0.92,2.42,12.35,11.81
std,0.86,0.72,1.5,0.33,0.0,5.16,1.95,1.90,2.93,5.42,5.28
min,0.00,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.00,3.00,3.00
25%,0.00,0.00,0.0,0.00,0.0,2.25,0.00,0.00,1.00,9.00,9.00
50%,0.00,0.00,0.5,0.00,0.0,5.00,0.00,0.00,1.50,12.50,11.00
75%,0.75,0.00,1.0,0.00,0.0,10.50,0.00,0.75,2.75,16.00,15.75
max,3.00,3.00,5.0,1.00,0.0,19.00,9.00,7.00,12.00,22.00,20.00

In [37]:
df['Total_Estrategias'].describe().round(2)

count    26.00
mean     12.35
std       5.42
min       3.00
25%       9.00
50%      12.50
75%      16.00
max      22.00
Name: Total_Estrategias, dtype: float64

##### Porcentaje de tipos de estrategias usadas (en relación con el total de estrategias usadas)

In [38]:
columnas_estrategias_porcentajes = [
    col for col in df.columns if col.startswith("Pct_Uso")]

In [39]:
df[columnas_estrategias_porcentajes].describe().round(2)

,Pct_Uso_SQ001,Pct_Uso_SQ002,Pct_Uso_SQ003,Pct_Uso_SQ004,Pct_Uso_SQ005,Pct_Uso_SQ006,Pct_Uso_SQ007,Pct_Uso_SQ008,Pct_Uso_SQ009
count,26.00,26.00,26.00,26.00,26.0,26.00,26.00,26.00,26.00
mean,3.82,2.14,7.20,0.90,0.0,53.67,5.56,5.61,21.10
std,7.00,5.76,10.69,2.70,0.0,31.13,13.56,11.49,23.46
min,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00
25%,0.00,0.00,0.00,0.00,0.0,35.07,0.00,0.00,6.36
50%,0.00,0.00,2.28,0.00,0.0,52.78,0.00,0.00,12.22
75%,6.25,0.00,10.42,0.00,0.0,80.94,0.00,4.41,25.00
max,25.00,22.22,41.67,11.11,0.0,100.00,56.25,41.67,85.71

In [40]:
columnas_other = [
    col for col in df.columns if col.startswith("E") and "[other]" in col
]
respuestas_texto = []

for col in columnas_other:
    serie_limpia = df[col].dropna().astype(str).str.strip()
    serie_valida = serie_limpia[
        ~serie_limpia.isin(["", "0", "nan", "None", "NaN"])
    ]

    respuestas_texto.extend(serie_limpia.tolist())

serie_otras_estrategias = pd.Series(respuestas_texto)
conteo_otras_estrategias = serie_otras_estrategias.value_counts()

print("Otras estrategias indicadas por los participantes:")
print(conteo_otras_estrategias)

Otras estrategias indicadas por los participantes:
0    520
Name: count, dtype: int64

##### Perfiles de usuarios de estrategias

Análisis de clústeres -> veáse ... (otro notebook) para más detalles

In [41]:
df['Cluster'].value_counts()

Cluster
Dicc/Trad    10
Prof+Dicc     6
IA            4
Prof          3
Combi         3
Name: count, dtype: int64

##### Número de palabras buscadas

Palabras registradas via Limesurvey o en la lista en papel

In [42]:
df['Total_Palabras_Buscadas'].describe().round(2)

count    26.00
mean     11.81
std       5.28
min       3.00
25%       9.00
50%      11.00
75%      15.75
max      20.00
Name: Total_Palabras_Buscadas, dtype: float64

##### Ratio estrategias - palabras buscadas

In [43]:
df['Estrategias_Por_Palabra'].describe().round(2)

count    26.00
mean      1.05
std       0.16
min       0.93
25%       1.00
50%       1.00
75%       1.00
max       1.70
Name: Estrategias_Por_Palabra, dtype: float64

##### Evaluación determinación correcta del significado de las palabras buscadas

- C: Correcto [1 punto]
- O: Otro significado correcto (incorrecto en este contexto) [0 puntos]
- P: Parcialmente correcto [0,5]
- F: Falso [0]
- N: No significado aportado [0]

In [44]:
columnas_totales_ev = [col for col in df.columns if col.endswith("_Ev")]

evaluaciones = []

for col in columnas_totales_ev:
    serie_limpia = df[col].dropna().astype(str).str.strip().str.replace("С", "C")
    serie_valida = serie_limpia[
        ~serie_limpia.isin(["", "0", "nan", "None", "NaN"])
    ]

    evaluaciones.extend(serie_valida.tolist())

serie_evaluaciones = pd.Series(evaluaciones)
serie_evaluaciones.value_counts()

C    272
P     21
F     13
O      1
Name: count, dtype: int64

In [45]:
serie_evaluaciones.value_counts(normalize=True).round(2)

C    0.89
P    0.07
F    0.04
O    0.00
Name: proportion, dtype: float64

##### Porcentaje de palabras determinadas correctamente

In [46]:
df['Pct_det'].describe().round(2)

count     26.00
mean      89.02
std        9.44
min       62.50
25%       85.62
50%       90.00
75%       95.84
max      100.00
Name: Pct_det, dtype: float64

##### Evaluación del resumen

In [47]:
df['Resumen'].value_counts()

Resumen
2.0    17
3.0     6
1.0     2
0.0     1
Name: count, dtype: int64

### Test de vocabulario

In [48]:
columnas_totales_ev = [col for col in df_voc.columns if col.endswith("_Ev")]

Se asigna una puntuación a la evaluación y se calcula el porcentaje de palabras acertadas.

##### Puntos conseguidos por palabras (parcialmente) correctas

In [49]:
df_voc['Ret_sum'] = df_voc[columnas_totales_ev].replace({"C":1,
                                                        "O":1,
                                                        "P":0.5,
                                                        "F":0,
                                                        "N":0}).apply(pd.to_numeric, errors="coerce").sum(axis=1)

In [50]:
df_voc['Ret_sum'].describe().round(2)

count    24.00
mean     12.10
std       4.24
min       5.00
25%      10.12
50%      11.75
75%      15.75
max      18.50
Name: Ret_sum, dtype: float64

##### Porcentaje de palabras correctas

(Palabras parcialmente correctas cuentan la mitad.)

In [51]:
df_voc['Pct_ret'] = (df_voc['Ret_sum']*10)/2

In [52]:
df_voc['Pct_ret'].describe().round(2)

count    24.00
mean     60.52
std      21.19
min      25.00
25%      50.62
50%      58.75
75%      78.75
max      92.50
Name: Pct_ret, dtype: float64