## Análisis Chino

In [28]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

#### Importar datos

In [29]:
df = pd.read_pickle("data_final")

In [30]:
df = df[df["Idioma"] == "Chino"]

In [31]:
df_voc = pd.read_excel("Chino_Voc.xlsx")

##### Uso de tipo de estrategias en el grupo

Estrategias usadas (a elegir, selección múltiple):
- SQ001: Usar mis conocimientos de otros idiomas (lengua materna u otras lenguas extranjeras)
- SQ002: Analizar la forma de la palabra o sus partes
- SQ003: Sacar conclusiones del contexto inmediato (p.ej. relación con otras palabras en la frase)
- SQ004: Sacar conclusiones del contexto general (p.ej. tema del texto o de la clase)
- SQ005: Fijarme en elementos no verbales (p.ej. imágenes, el formato del texto)
- SQ006: Consultar un diccionario o un traductor online
- SQ007: Usar una aplicación de Inteligencia Artificial (p.ej. Chat GPT)
- SQ008: Preguntar a un/a compañero/a
- SQ009: Preguntar al/a la docente

In [32]:
columnas_estrategias = [
    col for col in df.columns if col.startswith("E") and "[SQ" in col
]

In [33]:
frecuencias_totales = {}

for col in columnas_estrategias:
    codigo_estrategia = col.split("[")[1].split("]")[0]

    votos = df[col].sum()
    frecuencias_totales[codigo_estrategia] = (
        frecuencias_totales.get(codigo_estrategia, 0) + votos
    )

In [34]:
df_resultados = pd.DataFrame(
    list(frecuencias_totales.items()), columns=["Estrategia", "Frecuencia"]
)
total_elecciones = df_resultados["Frecuencia"].sum().astype(int)
df_resultados["Porcentaje"] = np.round(((
    df_resultados["Frecuencia"] / total_elecciones
) * 100), 2)

In [35]:
df_resultados_gen = df_resultados.replace({'SQ001': 'Otros idiomas', 
                        'SQ002': 'Analizar forma',
                        'SQ003': 'Contexto inmediato',
                      'SQ004': 'Contexto general',
                      'SQ005': 'Elementos no verbales',
                      'SQ006': 'Diccionario/Traductor',
                      'SQ007': 'Aplicación IA',
                      'SQ008': 'Preguntar compañero/a',
                      'SQ009': 'Preguntar profesor/a'})
df_resultados_gen

              Estrategia  Frecuencia  Porcentaje
0          Otros idiomas         6.0        1.02
1         Analizar forma        39.0        6.66
2     Contexto inmediato       114.0       19.45
3       Contexto general        90.0       15.36
4  Elementos no verbales        15.0        2.56
5  Diccionario/Traductor       275.0       46.93
6          Aplicación IA         6.0        1.02
7  Preguntar compañero/a        20.0        3.41
8   Preguntar profesor/a        21.0        3.58

##### Palabras marcadas como nuevas

In [36]:
df['Num'].describe().round(2)

count    57.00
mean     12.79
std       9.33
min       0.00
25%       9.00
50%      11.00
75%      14.00
max      58.00
Name: Num, dtype: float64

##### Número de estrategias indicadas (total y por tipo de estrategias)

In [37]:
columnas_estrategias_totales = [
    col for col in df.columns if col.startswith("Total")]

In [38]:
df[columnas_estrategias_totales].describe().round(2)

,Total_SQ001,Total_SQ002,Total_SQ003,Total_SQ004,Total_SQ005,Total_SQ006,Total_SQ007,Total_SQ008,Total_SQ009,Total_Estrategias,Total_Palabras_Buscadas
count,57.00,57.00,57.00,57.00,57.00,57.00,57.00,57.00,57.00,57.00,57.00
mean,0.11,0.68,2.00,1.58,0.26,4.82,0.11,0.35,0.37,10.28,8.51
std,0.45,1.28,2.04,1.77,0.48,3.52,0.49,0.79,0.77,5.67,4.21
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.00,1.00
25%,0.00,0.00,0.00,0.00,0.00,3.00,0.00,0.00,0.00,5.00,6.00
50%,0.00,0.00,1.00,1.00,0.00,4.00,0.00,0.00,0.00,10.00,8.00
75%,0.00,1.00,3.00,2.00,0.00,7.00,0.00,0.00,0.00,14.00,11.00
max,3.00,6.00,7.00,7.00,2.00,17.00,3.00,4.00,3.00,29.00,20.00

In [39]:
df['Total_Estrategias'].describe().round(2)

count    57.00
mean     10.28
std       5.67
min       2.00
25%       5.00
50%      10.00
75%      14.00
max      29.00
Name: Total_Estrategias, dtype: float64

##### Porcentaje de tipos de estrategias usadas (en relación con el total de estrategias usadas)

In [40]:
columnas_estrategias_porcentajes = [
    col for col in df.columns if col.startswith("Pct_Uso")]

In [41]:
df[columnas_estrategias_porcentajes].describe().round(2)

,Pct_Uso_SQ001,Pct_Uso_SQ002,Pct_Uso_SQ003,Pct_Uso_SQ004,Pct_Uso_SQ005,Pct_Uso_SQ006,Pct_Uso_SQ007,Pct_Uso_SQ008,Pct_Uso_SQ009
count,57.00,57.00,57.00,57.00,57.00,57.00,57.00,57.00,57.00
mean,1.13,5.38,17.18,14.51,2.39,49.20,2.66,2.88,4.67
std,5.06,9.85,14.77,14.82,4.82,31.04,14.04,5.97,10.33
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.00,0.00,0.00,0.00,0.00,25.00,0.00,0.00,0.00
50%,0.00,0.00,20.00,11.11,0.00,46.15,0.00,0.00,0.00
75%,0.00,6.67,26.67,25.00,0.00,75.00,0.00,0.00,0.00
max,33.33,40.00,50.00,50.00,20.00,100.00,100.00,23.08,50.00

In [42]:
columnas_other = [
    col for col in df.columns if col.startswith("E") and "[other]" in col
]
respuestas_texto = []

for col in columnas_other:
    serie_limpia = df[col].dropna().astype(str).str.strip()
    serie_valida = serie_limpia[
        ~serie_limpia.isin(["", "0", "nan", "None", "NaN"])
    ]

    respuestas_texto.extend(serie_limpia.tolist())

serie_otras_estrategias = pd.Series(respuestas_texto)
conteo_otras_estrategias = serie_otras_estrategias.value_counts()

print("Otras estrategias indicadas por los participantes:")
print(conteo_otras_estrategias)

Otras estrategias indicadas por los participantes:
0                                                                                     853
NO                                                                                    172
diccionario                                                                            25
traductor                                                                               7
Google                                                                                  7
contexto                                                                                6
móvil - Pleco chinese dictionary                                                        4
buscar en el diccionario                                                                4
diccionario/prof                                                                        3
Libro chino                                                                             3
Conocimiento                                                                            3
por el contexto                                                                         3
Cámara para traducir                                                                    2
consultado en un traductor online                                                       2
Buscando en internet                                                                    2
mediante aplicación de traducción                                                       2
preguntar a la profesora                                                                2
Lo recordé                                                                              2
contexto/libro de texto                                                                 2
por el contexto en el texto                                                             2
por el contexto en el texto, ya que se parece a 头 (comprar) por lo que será vender      1
profesora                                                                               1
pregunta a un compañero                                                                 1
he recordado que era un apellido                                                        1
buscador online                                                                         1
preguntar a la docente                                                                  1
Buscar apuntes                                                                          1
Que es un nombre por contexto y el pinuin buscando en google                            1
Por analogía                                                                            1
le he preguntado a una compañera                                                        1
Vocab                                                                                   1
Lo vimos en clase, pero no conozco el pinyin ni sabría escribirlo                       1
Libro de texto                                                                          1
contexto, diccionario                                                                   1
diccionario y wikipedia                                                                 1
miré apuntes                                                                            1
le he preguntado la la docente ya que pensaba que era otra cosa                         1
consultado en una página web                                                            1
buscar imágenes en Google                                                               1
forma 《》/libro texto                                                                    1
consultado en los apuntes tomados en clase                                              1
traductor online                                                                        1
contexto/profesora                                                                      1
Conozco 亲 y por el contexto del formato de la carta                                     1
Buscar en internet                                                                      1
me he acordado/contexto                                                                 1
pregunté a la profesora                                                                 1
deducido por el contexto                                                                1
ver cómo se decía cada caracter y contexto                                              1
prof                                                                                    1
deducido por el contexto/consultado en el libro de texto                                1
app                                                                                     1
preguntar a mi compañera                                                                1
Libro de texto/google                                                                   1
Name: count, dtype: int64

##### Perfiles de usuarios de estrategias

Análisis de clústeres -> veáse ... (otro notebook) para más detalles

In [43]:
df['Cluster'].value_counts()

Cluster
Combi        21
Dicc/Trad    15
Contexto     14
Prof+Dicc     5
IA            2
Name: count, dtype: int64

##### Número de palabras buscadas

Palabras registradas via Limesurvey o en la lista en papel

In [44]:
df['Total_Palabras_Buscadas'].describe().round(2)

count    57.00
mean      8.51
std       4.21
min       1.00
25%       6.00
50%       8.00
75%      11.00
max      20.00
Name: Total_Palabras_Buscadas, dtype: float64

##### Ratio estrategias - palabras buscadas

In [45]:
df['Estrategias_Por_Palabra'].describe().round(2)

count    57.00
mean      1.25
std       0.45
min       0.29
25%       1.00
50%       1.10
75%       1.40
max       3.00
Name: Estrategias_Por_Palabra, dtype: float64

##### Evaluación determinación correcta del significado de las palabras buscadas

- C: Correcto [1 punto]
- O: Otro significado correcto (incorrecto en este contexto) [0 puntos]
- P: Parcialmente correcto [0,5]
- F: Falso [0]
- N: No significado aportado [0]

In [46]:
columnas_totales_ev = [col for col in df.columns if col.endswith("_Ev")]

evaluaciones = []

for col in columnas_totales_ev:
    serie_limpia = df[col].dropna().astype(str).str.strip().str.replace("С", "C")
    serie_valida = serie_limpia[
        ~serie_limpia.isin(["", "0", "nan", "None", "NaN"])
    ]

    evaluaciones.extend(serie_valida.tolist())

serie_evaluaciones = pd.Series(evaluaciones)
serie_evaluaciones.value_counts()

C    366
P     57
F     32
N     18
O     13
Name: count, dtype: int64

In [47]:
serie_evaluaciones.value_counts(normalize=True).round(2)

C    0.75
P    0.12
F    0.07
N    0.04
O    0.03
Name: proportion, dtype: float64

##### Porcentaje de palabras determinadas correctamente

In [48]:
df['Pct_det'].describe().round(2)

count     57.00
mean      82.55
std       21.73
min        0.00
25%       75.00
50%       90.00
75%      100.00
max      100.00
Name: Pct_det, dtype: float64

##### Evaluación del resumen

In [49]:
df['Resumen'].value_counts()

Resumen
3.0    32
2.0    15
1.0    10
Name: count, dtype: int64

### Test de vocabulario

In [50]:
columnas_totales_ev = [col for col in df_voc.columns if col.endswith("_Ev")]

Se asigna una puntuación a la evaluación y se calcula el porcentaje de palabras acertadas.

##### Puntos conseguidos por palabras (parcialmente) correctas

In [51]:
df_voc['Ret_sum'] = df_voc[columnas_totales_ev].replace({"C":1,
                                                        "O":1,
                                                        "P":0.5,
                                                        "F":0,
                                                        "N":0}).apply(pd.to_numeric, errors="coerce").sum(axis=1)

In [52]:
df_voc['Ret_sum'].describe().round(2)

count    52.00
mean      9.88
std       4.75
min       0.00
25%       6.50
50%      10.00
75%      13.00
max      20.00
Name: Ret_sum, dtype: float64

##### Porcentaje de palabras correctas

(Palabras parcialmente correctas cuentan la mitad.)

In [53]:
df_voc['Pct_ret'] = (df_voc['Ret_sum']*10)/2

In [54]:
df_voc['Pct_ret'].describe().round(2)

count     52.00
mean      49.42
std       23.74
min        0.00
25%       32.50
50%       50.00
75%       65.00
max      100.00
Name: Pct_ret, dtype: float64