## Análisis Alemán

In [52]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

#### Importar datos

In [53]:
df = pd.read_pickle("data_final")

In [54]:
df = df[df["Idioma"] == "Alemán"]

In [55]:
df_voc = pd.read_excel("Aleman_Voc.xlsx")

### Tarea y encuesta

##### Uso de tipo de estrategias en el grupo

Estrategias usadas (a elegir, selección múltiple):
- SQ001: Usar mis conocimientos de otros idiomas (lengua materna u otras lenguas extranjeras)
- SQ002: Analizar la forma de la palabra o sus partes
- SQ003: Sacar conclusiones del contexto inmediato (p.ej. relación con otras palabras en la frase)
- SQ004: Sacar conclusiones del contexto general (p.ej. tema del texto o de la clase)
- SQ005: Fijarme en elementos no verbales (p.ej. imágenes, el formato del texto)
- SQ006: Consultar un diccionario o un traductor online
- SQ007: Usar una aplicación de Inteligencia Artificial (p.ej. Chat GPT)
- SQ008: Preguntar a un/a compañero/a
- SQ009: Preguntar al/a la docente

In [56]:
columnas_estrategias = [
    col for col in df.columns if col.startswith("E") and "[SQ" in col
]

In [57]:
frecuencias_totales = {}

for col in columnas_estrategias:
    codigo_estrategia = col.split("[")[1].split("]")[0]

    votos = df[col].sum()
    frecuencias_totales[codigo_estrategia] = (
        frecuencias_totales.get(codigo_estrategia, 0) + votos
    )

In [58]:
df_resultados = pd.DataFrame(
    list(frecuencias_totales.items()), columns=["Estrategia", "Frecuencia"]
)
total_elecciones = df_resultados["Frecuencia"].sum().astype(int)
df_resultados["Porcentaje"] = np.round(((
    df_resultados["Frecuencia"] / total_elecciones
) * 100), 2)

In [59]:
df_resultados_gen = df_resultados.replace({'SQ001': 'Otros idiomas', 
                        'SQ002': 'Analizar forma',
                        'SQ003': 'Contexto inmediato',
                      'SQ004': 'Contexto general',
                      'SQ005': 'Elementos no verbales',
                      'SQ006': 'Diccionario/Traductor',
                      'SQ007': 'Aplicación IA',
                      'SQ008': 'Preguntar compañero/a',
                      'SQ009': 'Preguntar profesor/a'})
df_resultados_gen

              Estrategia  Frecuencia  Porcentaje
0          Otros idiomas        53.0        4.95
1         Analizar forma       137.0       12.80
2     Contexto inmediato       139.0       12.99
3       Contexto general        74.0        6.92
4  Elementos no verbales        10.0        0.93
5  Diccionario/Traductor       600.0       56.07
6          Aplicación IA        36.0        3.36
7  Preguntar compañero/a        21.0        1.96
8   Preguntar profesor/a         0.0        0.00

##### Palabras marcadas como nuevas

In [60]:
df['Num'].describe().round(2)

count    57.00
mean     23.70
std       9.74
min       2.00
25%      18.00
50%      23.00
75%      30.00
max      47.00
Name: Num, dtype: float64

##### Número de estrategias indicadas (total y por tipo de estrategias)

In [61]:
columnas_estrategias_totales = [
    col for col in df.columns if col.startswith("Total")]

In [62]:
df[columnas_estrategias_totales].describe().round(2)

,Total_SQ001,Total_SQ002,Total_SQ003,Total_SQ004,Total_SQ005,Total_SQ006,Total_SQ007,Total_SQ008,Total_SQ009,Total_Estrategias,Total_Palabras_Buscadas
count,57.00,57.00,57.00,57.00,57.00,57.00,57.00,57.00,57.0,57.00,57.00
mean,0.93,2.40,2.44,1.30,0.18,10.53,0.63,0.37,0.0,18.77,14.09
std,1.41,2.98,2.88,1.56,0.80,4.93,2.01,0.94,0.0,9.25,5.11
min,0.00,0.00,0.00,0.00,0.00,2.00,0.00,0.00,0.0,2.00,2.00
25%,0.00,0.00,0.00,0.00,0.00,7.00,0.00,0.00,0.0,13.00,10.00
50%,0.00,1.00,2.00,1.00,0.00,9.00,0.00,0.00,0.0,18.00,15.00
75%,1.00,4.00,3.00,2.00,0.00,14.00,0.00,0.00,0.0,23.00,19.00
max,5.00,13.00,13.00,6.00,5.00,20.00,13.00,4.00,0.0,53.00,20.00

In [63]:
df['Total_Estrategias'].describe().round(2)

count    57.00
mean     18.77
std       9.25
min       2.00
25%      13.00
50%      18.00
75%      23.00
max      53.00
Name: Total_Estrategias, dtype: float64

##### Porcentaje de tipos de estrategias usadas (en relación con el total de estrategias usadas)

In [64]:
columnas_estrategias_porcentajes = [
    col for col in df.columns if col.startswith("Pct_Uso")]

In [65]:
df[columnas_estrategias_porcentajes].describe().round(2)

,Pct_Uso_SQ001,Pct_Uso_SQ002,Pct_Uso_SQ003,Pct_Uso_SQ004,Pct_Uso_SQ005,Pct_Uso_SQ006,Pct_Uso_SQ007,Pct_Uso_SQ008,Pct_Uso_SQ009
count,57.00,57.00,57.00,57.00,57.00,57.00,57.00,57.00,57.0
mean,4.22,10.86,11.02,6.84,0.64,60.22,3.31,2.90,0.0
std,6.22,10.94,9.90,7.98,3.45,22.61,9.00,7.46,0.0
min,0.00,0.00,0.00,0.00,0.00,13.04,0.00,0.00,0.0
25%,0.00,0.00,0.00,0.00,0.00,42.86,0.00,0.00,0.0
50%,0.00,8.33,10.53,5.88,0.00,57.14,0.00,0.00,0.0
75%,7.14,17.95,17.65,8.70,0.00,76.00,0.00,0.00,0.0
max,27.27,36.36,39.13,33.33,25.00,100.00,46.67,33.33,0.0

In [66]:
columnas_other = [
    col for col in df.columns if col.startswith("E") and "[other]" in col
]
respuestas_texto = []

for col in columnas_other:
    serie_limpia = df[col].dropna().astype(str).str.strip()
    serie_valida = serie_limpia[
        ~serie_limpia.isin(["", "0", "nan", "None", "NaN"])
    ]

    respuestas_texto.extend(serie_limpia.tolist())

serie_otras_estrategias = pd.Series(respuestas_texto)
conteo_otras_estrategias = serie_otras_estrategias.value_counts()

print("Otras estrategias indicadas por los participantes:")
print(conteo_otras_estrategias)

Otras estrategias indicadas por los participantes:
0    1140
Name: count, dtype: int64

##### Perfiles de usuarios de estrategias

Análisis de clústeres -> veáse ... (otro notebook) para más detalles

In [67]:
df['Cluster'].value_counts()

Cluster
Combi        28
Dicc/Trad    23
IA            4
Contexto      2
Name: count, dtype: int64

##### Número de palabras buscadas

Palabras registradas via Limesurvey o en la lista en papel

In [68]:
df['Total_Palabras_Buscadas'].describe().round(2)

count    57.00
mean     14.09
std       5.11
min       2.00
25%      10.00
50%      15.00
75%      19.00
max      20.00
Name: Total_Palabras_Buscadas, dtype: float64

##### Ratio estrategias - palabras buscadas

In [69]:
df['Estrategias_Por_Palabra'].describe().round(2)

count    57.00
mean      1.36
std       0.47
min       0.86
25%       1.00
50%       1.20
75%       1.45
max       3.00
Name: Estrategias_Por_Palabra, dtype: float64

##### Evaluación determinación correcta del significado de las palabras buscadas

- C: Correcto [1 punto]
- O: Otro significado correcto (incorrecto en este contexto) [0 puntos]
- P: Parcialmente correcto [0,5]
- F: Falso [0]
- N: No significado aportado [0]

In [70]:
columnas_totales_ev = [col for col in df.columns if col.endswith("_Ev")]

evaluaciones = []

for col in columnas_totales_ev:
    serie_limpia = df[col].dropna().astype(str).str.strip().str.replace("С", "C")
    serie_valida = serie_limpia[
        ~serie_limpia.isin(["", "0", "nan", "None", "NaN"])
    ]

    evaluaciones.extend(serie_valida.tolist())

serie_evaluaciones = pd.Series(evaluaciones)
serie_evaluaciones.value_counts()

C    718
F     42
P     28
O     14
N      1
Name: count, dtype: int64

In [79]:
serie_evaluaciones.value_counts(normalize=True).round(2)

C    0.89
F    0.05
P    0.03
O    0.02
N    0.00
Name: proportion, dtype: float64

##### Porcentaje de palabras determinadas correctamente

In [71]:
df['Pct_det'].describe().round(2)

count     57.00
mean      87.49
std       12.26
min       55.00
25%       80.00
50%       90.62
75%      100.00
max      100.00
Name: Pct_det, dtype: float64

##### Evaluación del resumen

In [72]:
df['Resumen'].value_counts()

Resumen
2.0    26
1.0    19
3.0    10
0.0     2
Name: count, dtype: int64

### Test de vocabulario

In [73]:
columnas_totales_ev = [col for col in df_voc.columns if col.endswith("_Ev")]

Se asigna una puntuación a la evaluación y se calcula el porcentaje de palabras acertadas.

##### Puntos conseguidos por palabras (parcialmente) correctas

(Palabras parcialmente correctas cuentan la mitad.)

In [74]:
df_voc['Ret_sum'] = df_voc[columnas_totales_ev].replace({"C":1,
                                                        "O":1,
                                                        "P":0.5,
                                                        "F":0,
                                                        "N":0}).apply(pd.to_numeric, errors="coerce").sum(axis=1)

In [75]:
df_voc['Ret_sum'].describe().round(2)

count    32.00
mean     12.25
std       4.24
min       4.00
25%       9.00
50%      12.00
75%      14.62
max      20.00
Name: Ret_sum, dtype: float64

##### Porcentaje de palabras correctas

In [76]:
df_voc['Pct_ret'] = (df_voc['Ret_sum']*10)/2

In [77]:
df_voc['Pct_ret'].describe().round(2)

count     32.00
mean      61.25
std       21.22
min       20.00
25%       45.00
50%       60.00
75%       73.12
max      100.00
Name: Pct_ret, dtype: float64